export { default as Home} from './Home'
export { default as Consider} from './Consider'
export { default as Features} from './Features'
export { default as Focus} from './Focus'
export { default as Questions} from './Questions'
export { default as Specification} from './Specification'